# Generated by Django 5.2.6 on 2025-12-24 11:16

from django.db import migrations, models


def migrate_role_values(apps, schema_editor):
    """Migrate old role values to new role values."""
    UserProfile = apps.get_model("profiles", "UserProfile")
    db_alias = schema_editor.connection.alias

    # Update role values
    UserProfile.objects.using(db_alias).filter(role="ADMIN").update(role="TENANT_ADMIN")
    UserProfile.objects.using(db_alias).filter(role="BR").update(role="WORKS_COUNCIL")
    UserProfile.objects.using(db_alias).filter(role="MANAGER").update(role="MANAGEMENT")
    UserProfile.objects.using(db_alias).filter(role="GUEST").update(role="STAKEHOLDER")
    # LEGAL stays LEGAL


def reverse_migrate_role_values(apps, schema_editor):
    """Reverse migration for rollback (if needed)."""
    UserProfile = apps.get_model("profiles", "UserProfile")
    db_alias = schema_editor.connection.alias

    # Reverse role values
    UserProfile.objects.using(db_alias).filter(role="TENANT_ADMIN").update(role="ADMIN")
    UserProfile.objects.using(db_alias).filter(role="WORKS_COUNCIL").update(role="BR")
    UserProfile.objects.using(db_alias).filter(role="MANAGEMENT").update(role="MANAGER")
    UserProfile.objects.using(db_alias).filter(role="STAKEHOLDER").update(role="GUEST")


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name="userprofile",
            name="account_type",
            field=models.CharField(
                choices=[("INTERNAL", "Internal"), ("EXTERNAL", "External")],
                default="INTERNAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Migrate data: Update role values in DB (uses .update(), no model validation)
        # This runs BEFORE AlterField to change old values to new values
        migrations.RunPython(migrate_role_values, reverse_migrate_role_values),
        # Update role field choices (after data migration)
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("TENANT_ADMIN", "Tenant Admin"),
                    ("LEGAL", "Legal"),
                    ("WORKS_COUNCIL", "Works Council"),
                    ("MANAGEMENT", "Management"),
                    ("STAKEHOLDER", "Stakeholder"),
                ],
                default="STAKEHOLDER",
                max_length=20,
            ),
        ),
    ]
