# Generated by Django 5.2.6 on 2025-12-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_add_document_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="external_email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="external_email_frequency",
            field=models.CharField(
                choices=[("IMMEDIATE", "Immediate"), ("DAILY", "Daily")],
                default="IMMEDIATE",
                max_length=20,
            ),
        ),
    ]
