# Generated by Django 5.2.6 on 2025-12-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_add_external_email_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notify_on_comment_reply",
            field=models.BooleanField(default=True),
        ),
    ]
