# Generated by Django 5.2.6 on 2025-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("LEGAL", "Legal"),
                            ("BR", "BR"),
                            ("MANAGER", "Manager"),
                            ("GUEST", "Guest"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
