# Generated by Django 5.2.6 on 2025-12-24 11:19

from django.db import migrations, models


def migrate_expires_at_to_invitation_expires_at(apps, schema_editor):
    """Migrate old expires_at to invitation_expires_at."""
    Invitation = apps.get_model("users", "Invitation")
    db_alias = schema_editor.connection.alias

    # Copy expires_at to invitation_expires_at for all existing invitations
    for invitation in Invitation.objects.using(db_alias).filter(
        expires_at__isnull=False
    ):
        invitation.invitation_expires_at = invitation.expires_at
        invitation.save(update_fields=["invitation_expires_at"])


def reverse_migrate_invitation_expires_at(apps, schema_editor):
    """Reverse migration for rollback."""
    Invitation = apps.get_model("users", "Invitation")
    db_alias = schema_editor.connection.alias

    # Copy invitation_expires_at back to expires_at
    for invitation in Invitation.objects.using(db_alias).filter(
        invitation_expires_at__isnull=False
    ):
        invitation.expires_at = invitation.invitation_expires_at
        invitation.save(update_fields=["expires_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_invitation"),
    ]

    operations = [
        # Add new fields first (before removing old field)
        migrations.AddField(
            model_name="invitation",
            name="invitation_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this invitation expires (not user expiry)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="user_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the created user account expires (for EXTERNAL accounts)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="account_type",
            field=models.CharField(
                choices=[("INTERNAL", "Internal"), ("EXTERNAL", "External")],
                default="INTERNAL",
                max_length=20,
            ),
        ),
        # Migrate data from old expires_at to new invitation_expires_at
        migrations.RunPython(
            migrate_expires_at_to_invitation_expires_at,
            reverse_migrate_invitation_expires_at,
        ),
        # Remove old field after data migration
        migrations.RemoveField(
            model_name="invitation",
            name="expires_at",
        ),
        # Update role choices
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("TENANT_ADMIN", "Tenant Admin"),
                    ("LEGAL", "Legal"),
                    ("WORKS_COUNCIL", "Works Council"),
                    ("MANAGEMENT", "Management"),
                    ("STAKEHOLDER", "Stakeholder"),
                ],
                max_length=20,
            ),
        ),
    ]
