# Generated by Django 5.2.6 on 2026-01-07 08:25

from django.db import migrations


USER_ID_UUID_SQL = """
DO $$
DECLARE
    column_type text;
    r RECORD;
    col text;
BEGIN
    SELECT data_type
      INTO column_type
      FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = 'users_user'
       AND column_name = 'id';

    IF column_type = 'bigint' THEN
        TRUNCATE TABLE users_user CASCADE;

        CREATE TEMP TABLE tmp_user_fks AS
        SELECT conrelid::regclass::text AS table_name,
               conname,
               pg_get_constraintdef(oid) AS condef,
               array_agg(attname ORDER BY attnum) AS column_names
          FROM pg_constraint c
          JOIN pg_attribute a
            ON a.attrelid = c.conrelid
           AND a.attnum = ANY(c.conkey)
         WHERE c.confrelid = 'users_user'::regclass
           AND c.contype = 'f'
         GROUP BY conrelid, conname, condef;

        FOR r IN SELECT * FROM tmp_user_fks LOOP
            EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', r.table_name, r.conname);
            FOREACH col IN ARRAY r.column_names LOOP
                EXECUTE format(
                    'ALTER TABLE %s ALTER COLUMN %I TYPE uuid USING NULL::uuid',
                    r.table_name,
                    col
                );
            END LOOP;
        END LOOP;

        ALTER TABLE users_user ALTER COLUMN id DROP IDENTITY IF EXISTS;
        ALTER TABLE users_user ALTER COLUMN id TYPE uuid USING NULL::uuid;

        FOR r IN SELECT * FROM tmp_user_fks LOOP
            EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', r.table_name, r.conname, r.condef);
        END LOOP;

        DROP TABLE tmp_user_fks;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_id"),
    ]

    operations = [
        migrations.RunSQL(USER_ID_UUID_SQL, migrations.RunSQL.noop),
    ]
