# Generated by Django 5.2.6 on 2025-11-17 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0005_tenant_pii_deterministic_tenant_pii_hmac_secret_and_more"),
        ("documents", "0003_rename_documentingestionrun_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("phase", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="customers.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("source", models.CharField(blank=True, default="", max_length=128)),
                (
                    "workflow_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "collection_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cases.case",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_events",
                        to="documents.documentingestionrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_events",
                        to="customers.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["tenant", "status"], name="case_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["tenant", "external_id"], name="case_tenant_external_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_id"), name="case_unique_external_id"
            ),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["tenant", "event_type"], name="case_event_tenant_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="case_event_tenant_created_idx"
            ),
        ),
    ]
