# Generated by Django 5.2.6 on 2025-10-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentIngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant", models.CharField(max_length=255)),
                ("case", models.CharField(max_length=255)),
                ("run_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("queued_at", models.CharField(max_length=64)),
                ("started_at", models.CharField(blank=True, default="", max_length=64)),
                (
                    "finished_at",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("inserted_documents", models.IntegerField(blank=True, null=True)),
                ("replaced_documents", models.IntegerField(blank=True, null=True)),
                ("skipped_documents", models.IntegerField(blank=True, null=True)),
                ("inserted_chunks", models.IntegerField(blank=True, null=True)),
                ("invalid_document_ids", models.JSONField(blank=True, default=list)),
                ("document_ids", models.JSONField(blank=True, default=list)),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "embedding_profile",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "case"], name="documents_d_tenant_2901aa_idx"
                    ),
                    models.Index(
                        fields=["tenant", "run_id"],
                        name="documents_d_tenant_2c4d54_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "case"),
                        name="document_ingestion_run_unique_case",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentLifecycleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=255)),
                ("document_id", models.UUIDField()),
                (
                    "workflow_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("state", models.CharField(max_length=32)),
                ("changed_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True, default="")),
                ("policy_events", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "workflow_id"],
                        name="documents_d_tenant__816925_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "document_id", "workflow_id"),
                        name="document_lifecycle_unique_record",
                    )
                ],
            },
        ),
    ]
