# Generated by Django 5.2.6 on 2025-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentingestionrun",
            name="collection_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentlifecyclestate",
            name="ingestion_run_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentlifecyclestate",
            name="run_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentlifecyclestate",
            name="trace_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
