# Generated by Django 5.2.6 on 2025-11-17 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_backfill_case_records"),
        ("customers", "0005_tenant_pii_deterministic_tenant_pii_hmac_secret_and_more"),
        ("documents", "0003_rename_documentingestionrun_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=128)),
                ("collection_id", models.UUIDField()),
                ("type", models.CharField(blank=True, default="", max_length=64)),
                ("visibility", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_collections",
                        to="cases.case",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_collections",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "case"], name="doc_collection_tenant_case_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "key"), name="document_collection_unique_key"
                    )
                ],
            },
        ),
    ]
