# Generated by Django 5.2.6 on 2025-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
