# Generated by Django 5.2.6 on 2025-11-25 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0004_add_document_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameworkProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("kbv", "Konzernbetriebsvereinbarung"),
                            ("gbv", "Gesamtbetriebsvereinbarung"),
                            ("bv", "Betriebsvereinbarung"),
                            ("dv", "Dienstvereinbarung"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("gremium_identifier", models.CharField(max_length=128)),
                ("gremium_name_raw", models.CharField(max_length=255)),
                ("version", models.IntegerField(default=1)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("external_id", models.CharField(max_length=128)),
                ("source_document_id", models.UUIDField(blank=True, null=True)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("analysis_metadata", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_document_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="framework_profiles_source",
                        to="documents.documentcollection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="framework_profiles",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrameworkDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Agreement"),
                            ("annex", "Annex/Attachment"),
                            ("protocol", "Signing Protocol"),
                            ("amendment", "Amendment"),
                        ],
                        default="main",
                        max_length=32,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "annex_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framework_documents",
                        to="documents.documentcollection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="framework_documents",
                        to="customers.tenant",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documents.frameworkprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="frameworkprofile",
            index=models.Index(
                fields=["tenant", "agreement_type"], name="fp_tenant_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frameworkprofile",
            index=models.Index(
                fields=["tenant", "gremium_identifier", "is_current"],
                name="fp_tenant_gremium_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="frameworkprofile",
            index=models.Index(fields=["source_document_id"], name="fp_source_doc_idx"),
        ),
        migrations.AddConstraint(
            model_name="frameworkprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "gremium_identifier", "version"),
                name="framework_profile_unique_version",
            ),
        ),
        migrations.AddIndex(
            model_name="frameworkdocument",
            index=models.Index(
                fields=["tenant", "profile"], name="fd_tenant_profile_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frameworkdocument",
            index=models.Index(
                fields=["document_id"], name="framework_doc_document_id_idx"
            ),
        ),
    ]
