# Generated by Django 5.2.6 on 2025-11-26 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


def deduplicate_collection_keys(apps, schema_editor):
    DocumentCollection = apps.get_model("documents", "DocumentCollection")

    duplicate_groups = (
        DocumentCollection.objects.values("tenant_id", "key")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    for group in duplicate_groups.iterator():
        duplicates = (
            DocumentCollection.objects.filter(
                tenant_id=group["tenant_id"], key=group["key"]
            )
            .order_by("created_at", "id")
            .values_list("id", flat=True)
        )
        ids_to_delete = list(duplicates)[1:]
        if ids_to_delete:
            DocumentCollection.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_caseevent_graph_name"),
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0005_frameworkprofile_frameworkdocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcollection",
            name="embedding_profile",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hash", models.CharField(max_length=128)),
                ("source", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source"], name="document_source_idx"),
                    models.Index(fields=["hash"], name="document_hash_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "hash"), name="document_unique_source_hash"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentCollectionMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("added_by", models.CharField(default="system", max_length=255)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="documents.documentcollection",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentcollection",
            name="documents",
            field=models.ManyToManyField(
                related_name="collections",
                through="documents.DocumentCollectionMembership",
                to="documents.document",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcollection",
            index=models.Index(
                fields=["tenant", "embedding_profile"],
                name="doc_coll_tenant_profile_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcollectionmembership",
            index=models.Index(fields=["collection"], name="document_collection_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcollectionmembership",
            index=models.Index(fields=["document"], name="collection_document_idx"),
        ),
        migrations.RunPython(deduplicate_collection_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="documentcollectionmembership",
            constraint=models.UniqueConstraint(
                fields=("document", "collection"),
                name="document_collection_membership_unique",
            ),
        ),
    ]
