# Generated by Django 5.2.6 on 2025-11-28 00:00

import django.db.models.deletion
from django.db import migrations, models


def populate_document_tenants(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Membership = apps.get_model("documents", "DocumentCollectionMembership")
    Lifecycle = apps.get_model("documents", "DocumentLifecycleState")

    memberships = (
        Membership.objects.select_related("collection")
        .values("document_id", "collection__tenant_id")
        .order_by("document_id")
    )

    membership_map = {}
    for membership in memberships.iterator():
        membership_map.setdefault(membership["document_id"], set()).add(
            membership["collection__tenant_id"]
        )

    lifecycle_map = {}
    lifecycle_records = (
        Lifecycle.objects.values("document_id", "tenant_id").order_by("document_id")
    )
    for lifecycle_record in lifecycle_records.iterator():
        lifecycle_map.setdefault(lifecycle_record["document_id"], set()).add(
            lifecycle_record["tenant_id"]
        )

    for document in Document.objects.all().iterator():
        tenant_ids = set()
        tenant_ids.update(membership_map.get(document.id, set()))
        tenant_ids.update(lifecycle_map.get(document.id, set()))

        if len(tenant_ids) == 1:
            document.tenant_id = tenant_ids.pop()
            document.save(update_fields=["tenant"])
        elif len(tenant_ids) == 0:
            raise ValueError(
                "Cannot determine tenant for document %s; assign memberships or lifecycle records before migrating"%
                document.id
            )
        else:
            raise ValueError(
                "Document %s is associated with multiple tenants; normalize memberships before migrating"%
                document.id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0006_documentcollection_embedding_profile_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="customers.tenant",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="document",
            name="document_unique_source_hash",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="document_source_idx",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="document_hash_idx",
        ),
        migrations.RunPython(populate_document_tenants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="customers.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source", "hash"),
                name="document_unique_source_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=("tenant", "source"),
                name="document_tenant_source_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=("tenant", "hash"),
                name="document_tenant_hash_idx",
            ),
        ),
    ]
