# Generated by Django 5.2.6 on 2025-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_tenant_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentcollection",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
