# Generated by Django 5.2.6 on 2025-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0008_document_soft_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="lifecycle_state",
            field=models.CharField(db_index=True, default="pending", max_length=32),
        ),
        migrations.AddField(
            model_name="document",
            name="lifecycle_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "lifecycle_state"], name="doc_tenant_state_idx"
            ),
        ),
    ]
