# Generated by Django 5.2.6 on 2025-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_add_document_lifecycle_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentingestionrun",
            name="case",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
