# Generated by Django 5.2.6 on 2025-12-07 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0010_alter_documentingestionrun_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workflow_id", models.CharField(max_length=255)),
                ("asset_id", models.UUIDField()),
                ("collection_id", models.UUIDField(blank=True, null=True)),
                ("media_type", models.CharField(max_length=255)),
                ("blob_metadata", models.JSONField(blank=True, default=dict)),
                ("content", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_assets",
                        to="customers.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "document"], name="doc_asset_tenant_doc_idx"
                    ),
                    models.Index(
                        fields=["tenant", "asset_id"], name="doc_asset_tenant_asset_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "asset_id", "workflow_id"),
                        name="document_asset_unique_identity",
                    )
                ],
            },
        ),
    ]
