# Generated by Codex on 2025-12-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_documentasset"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentcollection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "collection_id"),
                name="unique_collection_id_per_tenant",
            ),
        ),
    ]
