# Generated by Django 5.2.6 on 2025-12-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0012_collection_id_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentlifecyclestate",
            name="tenant_id",
            field=models.ForeignKey(
                db_column="tenant_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.tenant",
                to_field="schema_name",
            ),
        ),
        migrations.AlterField(
            model_name="documentlifecyclestate",
            name="trace_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="documentlifecyclestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("run_id", ""),
                        models.Q(("ingestion_run_id", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("run_id", ""), _negated=True),
                        ("ingestion_run_id", ""),
                    ),
                    _connector="OR",
                ),
                name="lifecycle_runtime_id_xor",
            ),
        ),
    ]
