# Generated by Django 5.2.6 on 2025-12-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_remove_documentlifecyclestate"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="DocumentLifecycleState",
                ),
            ],
            database_operations=[],
        ),
    ]
