# Generated by Django 5.2.6 on 2025-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
        ("documents", "0015_delete_documentlifecyclestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="case_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Business case this document belongs to",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="trace_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trace ID for end-to-end correlation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="workflow_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Workflow that created/modified this document",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "case_id"], name="doc_tenant_case_idx"
            ),
        ),
    ]
