# Generated by Django 5.2.6 on 2025-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_add_context_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="trace_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trace ID for end-to-end correlation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="workflow_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Workflow that created/modified this document",
                max_length=255,
                null=True,
            ),
        ),
    ]
