# Generated by Django 5.2.6 on 2025-12-28 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_add_user_attribution_and_membership_actor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Viewed"),
                            ("DOWNLOAD", "Downloaded"),
                            ("SEARCH", "Found in Search"),
                            ("SHARE", "Shared"),
                            ("UPLOAD", "Uploaded"),
                            ("DELETE", "Deleted"),
                            ("TRANSFER", "Ownership Transferred"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "case_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Activity",
                "verbose_name_plural": "Document Activities",
                "indexes": [
                    models.Index(
                        fields=["document", "-timestamp"],
                        name="documents_d_documen_e399ab_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="documents_d_user_id_c33f31_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="documents_d_activit_e4baa3_idx",
                    ),
                    models.Index(
                        fields=["case_id", "-timestamp"],
                        name="documents_d_case_id_73ef43_idx",
                    ),
                ],
            },
        ),
    ]
