# Generated by Django 5.2.6 on 2025-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_tenant_alter_domain_tenant_delete_client"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("tenant",),
                name="unique_primary_domain_per_tenant",
            ),
        ),
    ]
