# Generated by Django 5.2.6 on 2025-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_tenant_add_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pii_deterministic",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_hmac_secret",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_logging_redaction",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_mode",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_name_detection",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_policy",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pii_post_response",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
