# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_tenant_pii_deterministic_tenant_pii_hmac_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="case_lifecycle_definition",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
