# Generated by Django 5.2.6 on 2025-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_tenant_case_lifecycle_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("ENTERPRISE", "Enterprise"), ("LAW_FIRM", "Law Firm")],
                default="ENTERPRISE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="works_council_scope",
            field=models.CharField(
                choices=[("ASSIGNED", "Assigned Cases Only"), ("ALL", "All Cases")],
                default="ALL",
                max_length=20,
            ),
        ),
    ]
