"""Shared HTTP header and request metadata constants."""

# Canonical header names
X_TENANT_ID_HEADER = "X-Tenant-ID"
X_TENANT_SCHEMA_HEADER = "X-Tenant-Schema"
X_CASE_ID_HEADER = "X-Case-ID"
X_TRACE_ID_HEADER = "X-Trace-ID"
X_INVOCATION_ID_HEADER = "X-Invocation-ID"
X_RUN_ID_HEADER = "X-Run-ID"
X_INGESTION_RUN_ID_HEADER = "X-Ingestion-Run-ID"
X_SERVICE_ID_HEADER = "X-Service-ID"
X_COLLECTION_ID_HEADER = "X-Collection-ID"
X_WORKFLOW_ID_HEADER = "X-Workflow-ID"
X_THREAD_ID_HEADER = "X-Thread-ID"
X_DOCUMENT_ID_HEADER = "X-Document-ID"
X_DOCUMENT_VERSION_ID_HEADER = "X-Document-Version-ID"
X_KEY_ALIAS_HEADER = "X-Key-Alias"
IDEMPOTENCY_KEY_HEADER = "Idempotency-Key"
X_RETRY_ATTEMPT_HEADER = "X-Retry-Attempt"

# Django request.META keys
META_TENANT_ID_KEY = "HTTP_X_TENANT_ID"
META_TENANT_SCHEMA_KEY = "HTTP_X_TENANT_SCHEMA"
META_CASE_ID_KEY = "HTTP_X_CASE_ID"
META_TRACE_ID_KEY = "HTTP_X_TRACE_ID"
META_INVOCATION_ID_KEY = "HTTP_X_INVOCATION_ID"
META_RUN_ID_KEY = "HTTP_X_RUN_ID"
META_INGESTION_RUN_ID_KEY = "HTTP_X_INGESTION_RUN_ID"
META_SERVICE_ID_KEY = "HTTP_X_SERVICE_ID"
META_COLLECTION_ID_KEY = "HTTP_X_COLLECTION_ID"
META_WORKFLOW_ID_KEY = "HTTP_X_WORKFLOW_ID"
META_THREAD_ID_KEY = "HTTP_X_THREAD_ID"
META_DOCUMENT_ID_KEY = "HTTP_X_DOCUMENT_ID"
META_DOCUMENT_VERSION_ID_KEY = "HTTP_X_DOCUMENT_VERSION_ID"
META_KEY_ALIAS_KEY = "HTTP_X_KEY_ALIAS"
META_IDEMPOTENCY_KEY = "HTTP_IDEMPOTENCY_KEY"
META_RETRY_ATTEMPT_KEY = "HTTP_X_RETRY_ATTEMPT"

# Workflow defaults
DEFAULT_WORKFLOW_PLACEHOLDER = "ad-hoc"

# Case-insensitive header lookups for task/request propagation
TRACE_ID_HEADER_CANDIDATES = (
    X_TRACE_ID_HEADER,
    "trace_id",
    "trace-id",
)
CASE_ID_HEADER_CANDIDATES = (
    X_CASE_ID_HEADER,
    "case_id",
    "case",
)
TENANT_ID_HEADER_CANDIDATES = (
    X_TENANT_ID_HEADER,
    "tenant",
    "tenant_id",
)
KEY_ALIAS_HEADER_CANDIDATES = (
    X_KEY_ALIAS_HEADER,
    "key_alias",
    "key-alias",
)
COLLECTION_ID_HEADER_CANDIDATES = (
    X_COLLECTION_ID_HEADER,
    "collection_id",
    "collection-id",
)
WORKFLOW_ID_HEADER_CANDIDATES = (
    X_WORKFLOW_ID_HEADER,
    "workflow_id",
    "workflow-id",
)
THREAD_ID_HEADER_CANDIDATES = (
    X_THREAD_ID_HEADER,
    "thread_id",
    "thread-id",
)

HEADER_CANDIDATE_MAP = {
    "trace_id": TRACE_ID_HEADER_CANDIDATES,
    "case_id": CASE_ID_HEADER_CANDIDATES,
    "tenant": TENANT_ID_HEADER_CANDIDATES,
    "key_alias": KEY_ALIAS_HEADER_CANDIDATES,
    "collection_id": COLLECTION_ID_HEADER_CANDIDATES,
    "workflow_id": WORKFLOW_ID_HEADER_CANDIDATES,
    "thread_id": THREAD_ID_HEADER_CANDIDATES,
}
