# Generated by Django 5.2.10 on 2026-01-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0001_rag_feedback"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ragfeedbackevent",
            new_name="ai_core_rag_tenant__68aeae_idx",
            old_name="ai_core_ra_tenant__5e9a6a_idx",
        ),
        migrations.RenameIndex(
            model_name="ragfeedbackevent",
            new_name="ai_core_rag_tenant__895141_idx",
            old_name="ai_core_ra_tenant__df7d31_idx",
        ),
        migrations.RenameIndex(
            model_name="ragrerankweight",
            new_name="ai_core_rag_tenant__624bc7_idx",
            old_name="ai_core_ra_tenant__47a31f_idx",
        ),
    ]
